### ISSUE TITLE
[Minor / Improvement] Create function to claim Scales from multiple scientists

### ISSUE THREAD

**Issue by BoxedFruits** [augmintedlabs/kaiju-p2e-bug-bounty#2]
https://github.com/augmintedlabs/kaiju-p2e-bug-bounty/blob/master/contracts/Scientists.sol#L233-L237

**Explanation:**

It would be nice to be able to claim  pending scales from multiple scientists. It would get a little annoying if you say, had 15 scientists and wanted to claim all at once since you would have to do 15 separate transactions.

**Comment by bagelface** [comment]
I think given the nature of the mint (i.e. one per wallet), we're going to pass on this feature. Though I'll try to convince Tyler to get you a mutant anyways for being the only one that submitted anything ;)
